/** @format */

// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
    {
      songName: "piya piya calling",
      artists: "Amanda Delara, Kaifi Khalil, Karpe",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "c01",
    },
    {
      songName: "Sochta Houn Remix",
      artists: "Nusrat Fateh Ali Khan",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l01",
    },
    {
      songName: "Heeriye",
      artists: "Jasleen Royal, Arijit Singh",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l02",
    },
    {
      songName: "Aasa Kooda (From Think Indie)",
      artists: "Sai Smriti, Sai Abhyankkar",
      language: "tamil",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l03",
    },
    {
      songName: "Dil Tu Jaan Tu - Gurnazar",
      artists: "Gurnazar",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l04",
    },
    {
      songName: "Guli Mata",
      artists: "Saad Lamjarred, Shreya Ghoshal",
      language: "hindi",
      origin: "non-local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l05",
    },
    {
      songName: "Tauba Tauba",
      artists: "Karan Aujla",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l06",
    },
    {
      songName: "King Shit",
      artists: "Shubh",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l07",
    },
    {
      songName: "Nadaaniyan",
      artists: "DJ Rahul Vaidya",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l08",
    },
    {
      songName: "o sajni rey",
      artists: "Arijit Singh",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l09",
    },
    {
      songName: "Soni Soni",
      artists: "Darshan Raval, Jonita Gandhi, Rochak Kohli",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l10",
    },
    {
      songName: "Water Packet",
      artists: "A. R. Rahman,Gana Kadhar, Shweta Mohan, Santhosh Narayanan",
      language: "tamil",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l11",
    },
    {
      songName: "You and Me",
      artists: "Shubh",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l12",
    },
    {
      songName: "Aaj Se Teri",
      artists: "Arijit Singh, Amit Trivedi",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l13",
    },
    {
      songName: "Thooriga",
      artists: "karthik",
      language: "tamil",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l14",
    },
    {
      songName: "Humraah",
      artists: "The Fusion Project, Sachet Tandon",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l15",
    },
    {
      songName: "Didi (Arabic)",
      artists: "Khaled",
      language: "arabic",
      origin: "non-local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "nl16",
    },
    {
      songName: "Good To Be",
      artists: "Mark Ambor",
      language: "english",
      origin: "non-local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "nl17",
    },
    {
      songName: "Our way",
      artists: "Mark Ambor",
      language: "english",
      origin: "non-local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "nl18",
    },
    {
      songName: "I hope It all works out",
      artists: "Mark Ambor",
      language: "english",
      origin: "non-local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "nl19",
    },
    {
      songName: "made in romania",
      artists: "Ionut Cercel",
      language: "romania",
      origin: "non-local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "nl20",
    },
    {
      songName: "saathiya",
      artists: "sonu nigam, A.R. Rahman, Gulzar",
      language: "hindi",
      origin: "local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "l21",
    },
    {
      songName: "I Ain't Worried",
      artists: "One Republic",
      language: "english",
      origin: "non-local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "nl22",
    },
    {
      songName: "Counting Stars",
      artists: "One Republic",
      language: "english",
      origin: "non-local",
      feelings: 5,
      img: "images/piya_calling.jpg",
      songId: "nl23",
    },
  ]);
}
